Adding support for Ubuntu 14.04 and 16.04
jtyr/ansible-sssd pull request #3
Opened 2017-02-25 15:46 UTC by drewstinnett

Howdy Jiri...great Ansible role!  We are looking to use it over here, but need to push it to some Ubuntu LTS hosts as well.  I tweaked the code a little bit and added some test suites in.  Everything appears to work correctly, so wanted to contribute it back over to you if you're interested.  Thanks!

Drew

2017-03-06 03:54 UTC, jtyr requested changes
Thank you for the PR. I have added several comments but I still need to review the testing part.

2017-03-06 03:54 UTC, jtyr commented on tasks/main.yaml
> +    that: (ansible_os_family == "RedHat") or (ansible_distribution == "Ubuntu")
Please change this to:

```
that: >
  ansible_os_family == "RedHat" or
  ansible_os_family == "Debian"
```

2017-03-06 03:54 UTC, jtyr commented on meta/main.yml
> +  - jtyr.config_encoder_filters
Please remove this change. To install the `config_encoder_filters` role, please follow the [installation instructions](https://github.com/jtyr/ansible-config_encoder_filters#installation).

2017-03-06 03:54 UTC, jtyr commented on meta/main.yml
> +    - name: Ubuntu
I would prefer if the additional supported platform would be Debian rather than Ubuntu.

2017-03-07 01:14 UTC, jtyr requested changes

2017-03-07 01:14 UTC, jtyr commented on tasks/main.yaml
> +        ansible_os_family == "RedHat" or
Please could you indent it by 2 chars only?

2017-03-07 01:15 UTC, drewstinnett commented on tasks/main.yaml
> +        ansible_os_family == "RedHat" or
For sure, updating now, thanks for pointing that out, bad copy/paste

2017-03-07 01:19 UTC, jtyr requested changes

2017-03-07 01:19 UTC, jtyr commented on meta/main.yml
> +        - 6
The role is fairly generic so it should work on `all` CentOS/RHEL distros. Please could you set the list of supported EL versions back to `- all`?

2017-03-07 01:22 UTC, drewstinnett commented on meta/main.yml
> +        - 6
Sure thing, reverting now

2017-03-07 01:23 UTC, jtyr requested changes

2017-03-07 01:23 UTC, jtyr commented on tests/test_inside_docker.sh
> +docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install jtyr.config_encoder_filters
I think you should use this command to pull the roll into the right directory:

```
ansible-galaxy install jtyr.config_encoder_filters,master,config_encoder_filters
```

2017-03-07 01:28 UTC, jtyr commented on meta/main.yml
> +
The last thing is to remove this empty line ;o)

2017-03-07 01:30 UTC, drewstinnett commented on meta/main.yml
> +
Done!

2017-03-07 01:37 UTC, jtyr commented
LGTM now. I will test it tomorrow and merge it if there is no problem.

2017-08-03 10:13 UTC, jtyr requested changes
Sorry, I dropped the ball. Trying to pick it up now ;o)

2017-08-03 10:13 UTC, jtyr commented on tests/inventory
> +localhost
Please could add this file into the `.gitignore`?

2017-08-03 10:13 UTC, jtyr commented on tests/test.yml
> +---
Please could you change the extension to `.yaml`? I kind of don't like the shorter `.yml`. It's like you would use `.jon` instead of `.json` ;o)

2017-08-03 10:13 UTC, jtyr commented on .travis.yml
> +# Testing hangs here, TODO:  Investigate
Did you manage to solve this problem?

2018-10-10 18:46 UTC, drewstinnett commented
I haven't had a chance to get back to this, so just going to close the request.  Thank you for all the input though!

2018-10-10 18:46 UTC, closed without merging